GET https://localhost:7220/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3R1c2VyIiwic3ViIjoidGVzdHVzZXIiLCJqdGkiOiJjMDRkODRhMyIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwMjAiLCJodHRwczovL2xvY2FsaG9zdDo3MjIwIl0sIm5iZiI6MTc3MjQ4NzE4MywiZXhwIjoxNzgwNDM1OTgzLCJpYXQiOjE3NzI0ODcxODQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.G03s-EOxwXw-uT6inqezbFLBrgnHpE-gLUn3RYARA0c

###
GET http://localhost:5020/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6InRlc3R1c2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwibmJmIjoxNzcyNDg3NjEyLCJleHAiOjE3NzI0OTEyMTIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMjAifQ.5_gUNZL6H0hgiRFazKiVwatVQwSpQtI8KHE88iJDZrc